"""migration

Revision ID: 3cf11465ba47
Revises: 
Create Date: 2024-04-18 11:32:00.241867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf11465ba47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communication_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Message', sa.String(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('AdminId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Publisher', sa.String(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Image', sa.String(), nullable=True),
    sa.Column('Amount', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typeOfPublication', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(), nullable=True),
    sa.Column('UnitPrice', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('Date', sa.String(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('platformId', sa.Integer(), nullable=True),
    sa.Column('publicationId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['platformId'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['publicationId'], ['publications.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.Integer(), nullable=True),
    sa.Column('referenceNo', sa.Integer(), nullable=True),
    sa.Column('paidVia', sa.String(), nullable=True),
    sa.Column('Date', sa.String(), nullable=True),
    sa.Column('OrderId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['OrderId'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('orders')
    op.drop_table('publications')
    op.drop_table('users')
    op.drop_table('platforms')
    op.drop_table('communication_channels')
    op.drop_table('admins')
    # ### end Alembic commands ###
