"""migrations

Revision ID: 86125298d298
Revises: 
Create Date: 2024-04-21 19:27:49.942552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86125298d298'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
