"""migration

Revision ID: 8ceebadd1495
Revises: 83799cff488c
Create Date: 2024-04-29 15:47:08.027935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ceebadd1495'
down_revision = '83799cff488c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('payments_OrderId_fkey', type_='foreignkey')
        batch_op.drop_column('OrderId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('OrderId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('payments_OrderId_fkey', 'orders', ['OrderId'], ['id'])

    # ### end Alembic commands ###
