"""serializing

Revision ID: b33eabeea2dc
Revises: b9048a0720ee
Create Date: 2024-04-24 11:12:01.069563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33eabeea2dc'
down_revision = 'b9048a0720ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
