"""serializing

Revision ID: b5bf68c185f8
Revises: b33eabeea2dc
Create Date: 2024-04-24 11:20:00.324683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5bf68c185f8'
down_revision = 'b33eabeea2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
