"""migrations

Revision ID: b9048a0720ee
Revises: 57b39139c452
Create Date: 2024-04-22 17:47:40.055102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9048a0720ee'
down_revision = '57b39139c452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communication_channels', sa.Column('userId', sa.Integer(), nullable=True))
    op.add_column('communication_channels', sa.Column('AdminId', sa.Integer(), nullable=True))
    op.drop_column('communication_channels', 'user_id')
    op.drop_column('communication_channels', 'admin_id')
    op.add_column('orders', sa.Column('userId', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('platformId', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('publicationId', sa.Integer(), nullable=True))
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_platform_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_publication_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'orders', 'publications', ['publicationId'], ['id'])
    op.create_foreign_key(None, 'orders', 'platforms', ['platformId'], ['id'])
    op.drop_column('orders', 'platform_id')
    op.drop_column('orders', 'user_id')
    op.drop_column('orders', 'publication_id')
    op.add_column('payments', sa.Column('OrderId', sa.Integer(), nullable=True))
    op.drop_constraint('payments_order_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['OrderId'], ['id'])
    op.drop_column('payments', 'order_id')
    op.add_column('publications', sa.Column('userId', sa.Integer(), nullable=True))
    op.drop_constraint('publications_user_id_fkey', 'publications', type_='foreignkey')
    op.create_foreign_key(None, 'publications', 'users', ['userId'], ['id'])
    op.drop_column('publications', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'publications', type_='foreignkey')
    op.create_foreign_key('publications_user_id_fkey', 'publications', 'users', ['user_id'], ['id'])
    op.drop_column('publications', 'userId')
    op.add_column('payments', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_order_id_fkey', 'payments', 'orders', ['order_id'], ['id'])
    op.drop_column('payments', 'OrderId')
    op.add_column('orders', sa.Column('publication_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_publication_id_fkey', 'orders', 'publications', ['publication_id'], ['id'])
    op.create_foreign_key('orders_platform_id_fkey', 'orders', 'platforms', ['platform_id'], ['id'])
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'])
    op.drop_column('orders', 'publicationId')
    op.drop_column('orders', 'platformId')
    op.drop_column('orders', 'userId')
    op.add_column('communication_channels', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('communication_channels', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('communication_channels', 'AdminId')
    op.drop_column('communication_channels', 'userId')
    # ### end Alembic commands ###
