"""relation

Revision ID: e7d09c88b16d
Revises: ce9d5b4e1a91
Create Date: 2024-04-30 07:38:27.559088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d09c88b16d'
down_revision = 'ce9d5b4e1a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('platform_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('orders_userId_fkey', type_='foreignkey')
        batch_op.drop_constraint('orders_publicationId_fkey', type_='foreignkey')
        batch_op.drop_constraint('orders_platformId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'platforms', ['platform_id'], ['id'])
        batch_op.create_foreign_key(None, 'publications', ['publication_id'], ['id'])
        batch_op.drop_column('platformId')
        batch_op.drop_column('userId')
        batch_op.drop_column('publicationId')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('payments_order_id_fkey', type_='foreignkey')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_constraint('publications_userId_fkey', type_='foreignkey')
        batch_op.drop_column('userId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('publications_userId_fkey', 'users', ['userId'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('payments_order_id_fkey', 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publicationId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('platformId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_platformId_fkey', 'platforms', ['platformId'], ['id'])
        batch_op.create_foreign_key('orders_publicationId_fkey', 'publications', ['publicationId'], ['id'])
        batch_op.create_foreign_key('orders_userId_fkey', 'users', ['userId'], ['id'])
        batch_op.drop_column('platform_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('publication_id')

    # ### end Alembic commands ###
